### ISSUE TITLE
Proposal: Introduce versioning and version alignment

### ISSUE THREAD

**Issue by mmanciop** [canonical/charm-relation-interfaces#1]
We know that the relation interface is at the moment lacking capabilities in terms of:

1. TLS
2. Authentication

The capabilities above are virtually certain to require either side of the relation to perform significant different logic than they do now, so current providers and requesters, even if they do not _fail outright_ when confronted with, say, and endpoint requiring TLS, they will not be able to set up their workloads to interoperate with that endpoint.

IMO, we should add an optional property, called `version` to the root objects for provider and consumer, to represent the version of the relation interface. If not set, the `version` is assumed to be `0`, and should correspond in terms of capabilities with the `LIBAPI` version 0 of the [`prometheus_remote_write` charm library](https://charmhub.io/prometheus-k8s/libraries/prometheus_remote_write).

Future versions of the relation schema will have different structures depending on the version. Provider and requester **should** always post to the relation interface the highest version they are capable off, and when receiving from the other side a version that they also support, "downgrade" the relation data they expose accordingly.

If one role in the relation receives relation data with a version it does not understand, it must do nothing in response. That charm may decide to go into `BlockedState`, to signal the incompatibility with to the Juju admin. (`WaitingState` seems not semantically correct because there is no guarantee that a common version will be agreed upon.) If the other side downgrades its relation data to a common version, the charm will then recover from the `BlockedState`.

**Comment by simskij** [comment]
We did implement simple versioning for the specs themselves, however not at runtime. Closing this as we're not likely to get further for the time being. This could very well be a future enhancement, so I'll label it accordingly.
