### ISSUE TITLE
How to share relation interface schemas between charms

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charm-relation-interfaces#121]
Issue:
the charms implementing a charm-relation-interfaces-backed relation need to have access to the pydantic schemas in `schema.py` for the interface. Right now we need to copy-paste the code and share it 'manually' or bake it in the charm lib.

It would be nice if we could expose the interfaces from a pypi package (for example) or in some other way, so all the charm needs to do is:
`from charm_relation_interfaces.foo.v0.bar import BarRequirerSchema`

**Comment by sed-i** [comment]
Related: https://github.com/canonical/charm-relation-interfaces/issues/111

**Comment by PietroPasotti** [comment]
not just related: duplicate. Forgot we had that one.
