### ISSUE TITLE
requirer/provider pattern

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charm-relation-interfaces#13]
It seems to me that this collection of interfaces is biased towards the provider/requirer pattern.
Which is perfectly fine, but we could explain/state this more clearly in the toplevel README.

Are we only going to spec here provider/requirer interfaces? Or also other types of interfaces? (e.g. rolling-ops or other 'relation models')?
If so: we can make this clear in the toplevel readme and each interface's own readme doesn't have to repeat it or rephrase it.
If not: we have to be more clear in how we state it on a per-interface basis, and realize that that will have an effect on how the testers are setup.

**Comment by simskij** [comment]
You're not talking nonsense, but I don't think the patterns you describe all fit within what we already have. For instance, a pub-sub model would be a provider/requirer where one of them exposes a list of unacknowledged messages and the other end is expected to ack them as they have been processed.
